### ISSUE TITLE
Story: "404" Screen for when the disease does not exist.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#12]
## As a user, I want to know that I entered the wrong disease code by being presented with a 404 page so that I can check my URL and ensure that I entered the correct information.

Use the 404 page that we use in other apps (glossary, drug dictionary, etc.)

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: Page Not Found displays when a user views a dynamic listing page with invalid disease parameter
Given user navigates to “/C123455”
And "trialListingPageType" is set to "Disease"
When the user has entered an incorrect disease
Then the system redirects users to a 404 page 
     Then page title on error page is "Page Not Found"
     And the search bar appears below the text
     And the following links and texts exist on the page: "We can't find the page you're looking for." Visit the homepage, browse by cancer type, or use the search below." "Have a question? Get in touch."
  
      | https://www.cancer.gov          | homepage      | 
      | https://www.cancer.gov/types    | cancer type   | 
      | https://www.cancer.gov/contact  | Get in touch  |
And the system returns a 404 status code
```
```gherkin
Given the application returns a "Page not found" message
 Then the title tag should be "Page Not Found"
  Then the page should contain the markup <meta name="prerender-status-code" content="404">
```
```gherkin
Scenario: Page Load Analytics fires for a 404 with invalid disease
 Given "trialListingPageType" is set to "Disease"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "siteName" is set to "National Cancer Institute"
 When the user navigates to "/c123456"
   Then page title on error page is "Page Not Found"
    And browser waits
   Then there should be an analytics event with the following details

| key                                          | value                                            |
| type                                         | PageLoad                                         |
| event                                        | TrialListingPageApp:Load:PageNotFound            |
| page.name                                    | www.cancer.gov/c123456                           |
| page.title                                   | Page Not Found                                   |
| page.metaTitle                               | Page Not Found                                   |
| page.language                                | english                                          |
| page.type                                    | nciAppModulePage                                 |
| page.channel                                 | Clinical Trials                                  |
| page.contentGroup                            | Clinical Trials: Custom                          |
| page.additionalDetails.trialListingPageType  | disease                                          |
```
### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes
Adding markup will allow a pre-renderer to detect the error and report the correct 404 status code.

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

## Solution
As had been designed, the higher order component that fetches the listing info will be responsible for showing the 404 when one of the parameters that is fetched returns a 404 from the API.

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Add logic to `CTLViewsHoC` to display `PageNotFound` for 404s
- [ ] Update unit test for `CTLViewsHoC`
- [ ] Add integration tests 

### Technical Notes
- More notes, or technical nuances/direction
