### ISSUE TITLE
Story: No Trials Found Page for Dynamic Listing Pages for disease

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#13]
## As a user, I want to know what other options are available for me if there are no matching trials for my selected disease or intervention, so that I can further engage with NCI.

This actually redirects to `/notrials?p1=[disease-code-or-purl]`

> **ESTIMATE** 3

### Acceptance Criteria

```gherkin
Scenario: Page redirects and displays No Trials Found Page for Disease
  Given user navigates to “/C1234”
  When no trials are returned for the disease
  Then the system redirects users to /notrials?p1=spiroplatin
  Then the system displays the H1 "Spiroplatin Clinical Trials"
  Then the system displays the message: “There are no NCI-supported clinical trials for spiroplatin at this time. You can try a new search or contact our Cancer Information Service to talk about options for clinical trials.”
  And the link "new search" to "/about-cancer/treatment/clinical-trials/search" appears on the page
  And the link "contact our Cancer Information Service" to "/contact" appears on the page
  And the system displays the banner for “Questions about Clinical Trials?”
  And the system displays the "Chat Now"
```

```gherkin
Scenario: Status Code Returned for no trials found for Disease
  Given user navigates to “/C1234”
  When no trials are returned for the disease
  Then the system redirects users to /notrials?p1=spiroplatin
  And the page contains meta tags with the following names
	| name                  | content 	                                       |
	| prerender-status-code | 302     		                               |
	| prerender-header | Location: https://localhost:3000/notrials?p1=spiroplatin  |
```

```gherkin
Scenario: User visits the no trials found page directly without redirect
  Given the user navigates to "/notrials?p1=C3037"
  Then page title on error page is "Page Not Found"
  And the text "We can't find the page you're looking for." appears on the page
  And the link "homepage" to "https://www.cancer.gov" appears on the page
  And the link "cancer type" to "https://www.cancer.gov/types" appears on the page
  And the link "Get in touch" to "https://www.cancer.gov/contact" appears on the page
  And the search bar appears below
```

```gherkin
Scenario: User visits disease trials listing page with invalid parameters
  And "cisBannerImgUrlLarge" is set to null
  And "cisBannerImgUrlSmall" is set to null
  When the user navigates to "?cfg=6"
  Then the error message "Missing or invalid 'cisBannerImgUrlLarge, cisBannerImgUrlSmall' provided to app initialization." appears on the page
```

```gherkin
Scenario: User visits manual trial listing page with invalid parameters
  And "cisBannerImgUrlLarge" is set to "img.jpeg"
  And "cisBannerImgUrlSmall" is set to "img1.jpeg"
  When the user navigates to "?cfg=7"
  Then the error message "Missing or invalid 'cisBannerImgUrlLarge, cisBannerImgUrlSmall' provided to app initialization." appears on the page
```

### Notes

* Requirements discussions with Bryan, Paul, Seyi, and Kate resulted in a few decisions about the /notrials route:
  * Only if the user gets redirected to the "/notrials" route with the correct parameters does the NoTrialsFound page show
  * If the user goes directly to the "/notrials" route, even with correct parameters, Page Not Found is displayed
  * Basically, we don't want to be able to directly access the "/notrials" route - only if redirected after no trials are found

* Requirements discussions with Victoria and Bryan resulted in a few decisions about the banner images:
  * The banner should only display on Disease and Intervention pages, not on Manual pages.
  * If banner image parameters are not present in the config for either the Disease or Intervention instances of the app, the app should error and display a message that these parameters are invalid.
  * If banner image parameters are present in the config for a Manual instance of the app, the app should error and display a message that these parameters are invalid.

* Requirements discussions with Paul and Lilian resulted in a slight change in design for the "Chat Now" button.
  * It is now an actual button, not an anchor link disguised as a button.
  * The styling is slightly different, with a 1px-wide black border around the button.
---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Add redirect logic to `Disease` for no trials found 
- [ ] Update unit test for `Disease`
- [ ] Add integration test

### Technical Notes
- More notes, or technical nuances/direction
