### ISSUE TITLE
Story: Update app module architecture with NCIDS components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#184]
## As a developer, I want to update the architecture of the app module, so that I can implement NCIDS components.

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: User sees USA Banner at the top of the page
  Given user is viewing the preview site
  When user navigates to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0&pn=1
  Then the user will see the usa-banner at the top of the page
```

```gherkin
Scenario: User sees USA Header at the top of the page
  Given user is viewing the preview site
  When user navigates to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0&pn=1
  Then the user will see the usa-header at the top of the page
    And the header image will be 288px x 38px at tablet large, tablet, mobile large, and mobile breakpoints
    And the header image will be 597px x 50px at desktop and widescreen breakpoints
```

```gherkin
Scenario: User sees USA Footer at the bottom of the page
  Given user is viewing the preview site
  When user navigates to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0&pn=1
  Then the user will see the usa-footer at the bottom of the page
```

```gherkin
Scenario: User sees Back to Top at the bottom of the page
  Given user is viewing the preview site
  When user navigates to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0&pn=1
    And the user scrolls down from the very top of the page
  Then the user will see the Back to Top button with the text "Back to Top" at desktop and mobile breakpoints
```

### Notes
With the creation of NCIDS, we are planning to update the app modules with the new NCIDS components. We will need to refactor the architecture of our app modules to support these new components. `cgov-react-app-playground` will be updated with the new architecture first. We will use that as a basis for updating the architecture for this app.

As part of this ticket, we will be implementing the new NCIDS components that will replace the current components.

---

### Prerequisites
- [ ] [React App Playground #97](https://github.com/NCIOCPL/cgov-react-app-playground/issues/97)

### Tasks
- [ ] Get NCIDS into build
- [ ] Update react-app-dev preview page (index.html) - Issue #9999
  - Remove common.css and use a new common css file that is like ncids-minimal.scss (similar to CGDP)
    - This will be based on the ncids-minimal.scss from `cgov-react-app-playground`
  - Needs to include usa-banner, nci-header, usa-footer
  - Needs to include side nav on app modules that display it (this is not part of ncids-minimal.scss)
    - This should be ncids-application-page.scss
- [ ] Update app module to use NCIDS
- [ ] Ticket in platform: add ncids-with-side-nav.scss

### Technical Notes
- More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
This was closed with #264.
