### ISSUE TITLE
Story: Display Listing Results for Intervention & Trial Type

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-listing-app#19]
## As a user, I would like to view the trial results for valid intervention and trial type code parameters on a dynamic trial listing page, along with links to the trial's description page, the brief summary of the trial, and the number of locations of the trial.

This should include:
- handling the routing for the intervention dynamic URL
- fetching the ListingInformation for the given disease parameter
- fetching the results from the CTS API
- displaying the title, intro text, and listing results
- pager
- setting the metadata
- analytics
- page not found when the intervention or trial type doesn't exist
- No Trials Found redirect page
- Redirect ugly URLs to pretty URLs

The title and intro text for the intervention and trial type listing page is set according to given parameters.
H1: [Trial Type] Clinical Trials Using [Intervention Name]
Intro text:
```
<p>Clinical trials are research studies that involve people. The clinical trials on this list are testing [trial type] methods using [intervention name]. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI.</p><p>NCI’s <a href=\"/about-cancer/treatment/clinical-trials/what-are-trials\">basic information about clinical trials</a> explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you.</p>
```

The metadata for the intervention and trial type listing pages is set according to the given parameters.
Title: [Trial Type] Clinical Trials Using [Intervention Name] - National Cancer Institute
Og title: [Trial Type] Clinical Trials Using [Intervention Name] - National Cancer Institute
Og url: [base host]/[intervention-friendly-name-or-codes]/[trial-type]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials testing [trial type] methods that use [intervention name]."
Canonical URL: [canonical-host]/[intervention-friendly-name-or-codes]/[trial type]

Steal the locations code from the CTS App.

> **ESTIMATE** 3

#### General page
```gherkin
Scenario: View dynamic listing page results with intervention and trial type parameters
  Given the user navigates to "/C1647/treatment"
  And "trialListingPageType" is set to "Intervention"
  Then the page displays the title 'Treatment Clinical Trials Using Trastuzumab'
    And the page displays the intro text under the title
    And  the page displays 'Trials 1-25 of 916' under the intro text
    And the pager displays aligned to left on the same line as the number of trials
    And each result displays the trial object's brief_title as a link to the trial's description page
    And each result displays the trial object's brief_summary below the link for the trial
    And each result displays 'Locations: # locations' below the description
```

#### Title/Intro Text
```gherkin
Scenario: View dynamic listing page title and intro text with intervention and trial type parameters
Given the user navigates to "/C1647/treatment"
And "trialListingPageType" is set to "Intervention"
  Then the system displays the page heading aka H1 as "Treatment Clinical Trials Using Trastuzumab"
  Then the system displays the following introductory text below the H1: "Clinical trials are research studies that involve people. The clinical trials on this list are testing treatment methods using trastuzumab. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI."
  Then the system displays a paragraph break
  Then the system displays a second paragraph: "NCI’s basic information about clinical trials explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you."
    And the text "basic information about clinical trials" links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/what-are-trials
  And the number of trials and pager displays below the intro text
  And the results appear below the number of trials and pager
```

#### Pager
``` gherkin
Scenario: Pager on dynamic listing page results with disease and trial type parameters
  Given the user navigates to "/C4872/treatment"
  And "trialListingPageType" is set to "Disease"
    Then the page title is "Treatment Clinical Trials for Breast Cancer"
   Then the system displays "Trials 1-25 of" "544"
    And the top pager is aligned to left on the same line as the number of trials on desktop and tablet
   And the bottom pager is aligned to left 
    And pager displays the following navigation options
      | pages  |
      | 1      |
      | 2      |
      | 3      |
      | ...    |
      | 22     |
      | Next > |
    And the page "1" is highlighted
```
```gherkin
Scenario: Mobile Pager Display
  Given user navigates to a listing page results URL
  Then the system returns the results page for cancer
    Then a horizontal rule is displayed below the "Trials 1-25 of XXX" 
    Then a top pager is displayed aligned to the right
    Then a horizontal rule is displayed below the pager
    Then the result items are displayed 
    Then a horizontal rule is displayed 
    Then the bottom pager is displayed aligned to the right
```

#### Metadata
```gherkin
Scenario: View dynamic listing page metadata with intervention and trial type parameters
  Given the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And "trialListingPageType" is set to "Intervention"
When user navigates to "/C1647/treatment"
  Then the title tag should be "Treatment Clinical Trials Using Trastuzumab - National Cancer Institute"
    And there is a meta tag with a property "og:title" and content "Treatment Clinical Trials Using Trastuzumab"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/trastuzumab/treatment"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials testing treatment methods that use trastuzumab."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/trastuzumab/treatment"
```

#### Analytics
```gherkin
  Scenario: Page Load Analytics fires when a user views a dynamic listing page with intervention and trial type parameters
    Given "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Clinical Trials"
       And "trialListingPageType" is set to "Intervention"
    When the user navigates to "/C1647/treatment"
    Then there should be an analytics event with the following details
      | key                                          | value                                                                               |
      | type                                         | PageLoad                                                                            |
      | event                                        | TrialListingApp:Load:Results                                                        |
      | page.name                                    | www.cancer.gov/about-cancer/treatment/trastuzumab/treatment                         |
      | page.title                                   | Treatment Clinical Trials Using Trastuzumab                                         |
      | page.metaTitle                               | Treatment Clinical Trials Using Trastuzumab  - National Cancer Institute            |
      | page.language                                | english                                                                             |
      | page.type                                    | nciAppModulePage                                                                    |
      | page.channel                                 | Clinical Trials                                                                     |
      | page.contentGroup                            | Clinical Trials: Custom                                                             |
      | page.publishedDate                           | 02/02/2011                                                                          |
      | page.additionalDetails.numberResults         | [(int) results total]                                                               |
      | page.additionalDetails.trialListingPageType  | intervention                                                                        |
      | page.additionalDetails.interventionName      | trastuzumab                                                                         |
      | page.additionalDetails.trialType             | treatment                                                                           |
```

#### Page Not Found for invalid Intervention or Trial Type
```gherkin
Scenario: Page Not Found displays when a user views a dynamic listing page with invalid intervention or trial type parameters
Given user navigates to “/C123456/chicken”
And "trialListingPageType" is set to "Intervention"
When the user has entered an incorrect intervention or trial type
Then the system redirects users to a 404 page 
     Then page title on error page is "Page Not Found"
     And the search bar appears below the text
     And the following links and texts exist on the page: "We can't find the page you're looking for." Visit the homepage, browse by cancer type, or use the search below." "Have a question? Get in touch."
  
      | https://www.cancer.gov          | homepage      | 
      | https://www.cancer.gov/types    | cancer type   | 
      | https://www.cancer.gov/contact  | Get in touch  |

     And the system returns a 404 status code
```
```gherkin
Given the application returns a "Page not found" message
  Then the page should contain the markup <meta name="prerender-status-code" content="404">
```
```gherkin
Scenario: Page Load Analytics fires for a 404 with invalid intervention or trial type
 Given "trialListingPageType" is set to "Intervention"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "siteName" is set to "National Cancer Institute"
 When the user navigates to "/C123456/chicken"
   Then page title on error page is "Page Not Found"
    And browser waits
   Then there should be an analytics event with the following details

| key                                          | value                                            |
| type                                         | PageLoad                                         |
| event                                        | TrialListingPageApp:Load:PageNotFound            |
| page.name                                    | www.cancer.gov/C123456/chicken                   |
| page.title                                   | Page Not Found                                   |
| page.metaTitle                               | Page Not Found                                   |
| page.language                                | english                                          |
| page.type                                    | nciAppModulePage                                 |
| page.channel                                 | Clinical Trials                                  |
| page.contentGroup                            | Clinical Trials: Custom                          |
| page.additionalDetails.trialListingPageType  | intervention                                     |
```

#### No Trials Found page
```gherkin
Scenario: Page redirects and displays No Trials Found Page for Intervention and Trial Type
Given user navigates to “/C90960/treatment”
And "trialListingPageType" is set to "Intervention"
  When no trials are returned for the intervention and trial type
  Then the system redirects users to /notrials?p1=insulin-beef&p2=treatment
  Then the system displays the H1
  Then the system displays the message: “There are no NCI-supported clinical trials for treatment using insulin beef at this time. You can try a new search or contact our Cancer Information Service to talk about options for clinical trials.”
Then the system displays the banner for “Questions about Clinical Trials?” 
```
```gherkin
Scenario: Status Code Returned for no trials found for Intervention and Trial Type
Given user navigates to “/C90960/treatment”
And "trialListingPageType" is set to "Intervention"
When no trials are returned for the intervention and trial type
Then the system redirects users to /notrials?p1=insulin-beef&p2=treatment
Then the page should return a 404 status code.
```

#### Redirect ugly URL to pretty URL
```gherkin
Scenario: Page redirects to pretty URL if codes are given for Intervention and Trial Type
Given user navigates to “/C1647/treatment”
And "trialListingPageType" is set to "Intervention"
  When a mapping exists for C1647
  Then the system should redirect the URL to “/trastuzumab/treatment”
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Add route for intervention and trial type
- [ ] Update config variables
- [ ] Add route params for intervention trial type
- [ ] Update intervention component
- [ ] Add unit test
- [ ] Add integration test
- [ ] Update no trials found
- [ ] Add contants for dynamic listing patterns

### Technical Notes
- More notes, or technical nuances/direction
