### ISSUE TITLE
Design Solution: Implement Filtering on Disease pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#195]
We need to determine a design for the filtering functionality on the Disease dynamic listing pages.

Filters:
- Subtype: combo box
- Stage: combo box
- Drug/Intervention: combo box
- Age: text input
- Location by ZIP Code: text input
- Radius: dropdown

Additional functionality:
- Information tooltips
- Individual filter clears

**Parent Issue:** #194 

### Resources
* [Figma](https://www.figma.com/design/aY8QxlRfooju5J8iatOPpT/Dynamic-Listing-Pages?node-id=832-3688&p=f&m=dev)

### Sub-Tasks
- [x] Develop design approaches
- [x] User testing of designs
- [x] Client approval of design direction
- [ ] Iterate with approach to finalize design

**Comment by monika-jaeger** [comment]
[File in Figma](https://www.figma.com/file/aY8QxlRfooju5J8iatOPpT/Clinical-Trials?type=design&node-id=8%3A2148&mode=design&t=udmlDenm16y2UNtT-1) started. Added user testing findings from Fall 2022 and Benchmarking. [WIP]
cc: @blilianyu @sarinapadilla

**Comment by sarinapadilla** [comment]
We've broken this down into two tickets:
* #195
* #199 
So closing this ticket!

**Comment by sarinapadilla** [comment]
We've broken this down into two tickets:
* #195
* #199 
So closing this ticket!

**Comment by sarinapadilla** [comment]
We have finished comps for release 2 and are updating them as any changes are made, so closing this ticket!
