### ISSUE TITLE
Design Solution: Implement Filtering on Intervention Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#199]
We need to determine a design for the filtering functionality on the Intervention dynamic listing pages. 

Filters:
- Cancer Type: combo box
- Subtype: combo box
- Stage: combo box
- Age: text input
- Location by ZIP Code: text input
- Radius: dropdown

Additional functionality:
- Information tooltips
- Individual filter clears

**Parent Issue:** #194 

### Resources
* [Figma](https://www.figma.com/design/aY8QxlRfooju5J8iatOPpT/Dynamic-Listing-Pages?node-id=832-3688&p=f&m=dev)

### Sub-Tasks
- [x] Develop design approaches
- [x] User testing of designs
- [x] Client approval of design direction
- [ ] Iterate with approach to finalize design

**Comment by sarinapadilla** [comment]
We have finished comps for release 2 and are updating them as any changes are made, so closing this ticket!
