### ISSUE TITLE
Story: Display Listing Results for Manual Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#20]
## As a user, I would like to view the trial results for a manual listing page that is given specific parameters, along with links to the trial's description page, the brief summary of the trial, and the number of locations of the trial.

This should include:
- handling the routing for the manual list page URL
- fetching the results from the CTS API using the given query
- displaying the title, intro text, and listing results
- setting the metadata
- analytics

> **ESTIMATE** 5

The metadata for the manual listing pages is set according to the given parameters.
Title: [Title of app module Drupal page] - National Cancer Institute
Og title: [Title of app module Drupal page] - National Cancer Institute
Og url: [base host]/clinical-trials/[manual-page-url]
Description: [Meta description from app module Drupal page]
Canonical URL: [canonical-host]/clinical-trials/[manual-page-url]

Steal the locations code from the CTS App.

> **ESTIMATE** 5

#### General page
```gherkin
Scenario: View manual listing page results
  Given the user navigates to /clinical-trials/adult-metastatic-brain-tumors
  Then the page displays the title 'Treatment Clinical Trials for Adult Metastatic Brain Tumors'
    And the page displays the intro text under the title
    And  the page displays 'Trials 1-25 of 916' under the intro text
    And each result displays the trial object's brief_title as a link to the trial's description page
    And each result displays the trial object's brief_summary below the link for the trial
    And each result displays 'Locations: # locations' below the description
```

#### Title/Intro Text
```gherkin
Scenario: View manual listing page title and intro text
Given the user navigates to "/clinical-trials/adult-metastatic-brain-tumors"
  Then the system displays the page heading aka H1 as "Treatment Clinical Trials for Adult Metastatic Brain Tumors"
  Then the system displays the following introductory text below the H1: "Clinical trials are research studies that involve people. The clinical trials on this list are for adult metastatic brain tumor treatment. All trials on the list are supported by NCI."
  Then the system displays a paragraph break
  Then the system displays a second paragraph: "NCI’s basic information about clinical trials explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you."
    And the text "basic information about clinical trials" links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/what-are-trials
  And the number of trials and pager displays below the intro text
  And the results appear below the number of trials and pager
```

#### Metadata
```gherkin
Scenario: View manual listing page metadata
  Given the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is "/clinical-trials"
When the user navigates to "/clinical-trials/adult-metastatic-brain-tumors"
  Then the title tag should be "Treatment Clinical Trials for Adult Metastatic Brain Tumors - National Cancer Institute"
    And there is a meta tag with a property "og:title" and content "Treatment Clinical Trials for Adult Metastatic Brain Tumors - National Cancer Institute"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/clinical-trials/adult-metastatic-brain-tumors"
    And there is a meta tag with a property "description" and content "Find clinical trials to treat adult metastatic brain tumors."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/clinical-trials/adult-metastatic-brain-tumors"
```

#### Analytics
```gherkin
  Scenario: Page Load Analytics fires when a user views a manual listing page
    Given "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Clinical Trials"
    When the user navigates to "/clinical-trials/adult-metastatic-brain-tumors"
    Then there should be an analytics event with the following details
      | key                                         | value                                                                                   |
      | type                                        | PageLoad                                                                                |
      | event                                       | TrialListingApp:Load:Results                                                            |
      | page.name                                   | www.cancer.gov/about-cancer/treatment/clinical-trials/adult-metastatic-brain-tumors     |
      | page.title                                  | Treatment Clinical Trials for Adult Metastatic Brain Tumors                             |
      | page.metaTitle                              | Treatment Clinical Trials for Adult Metastatic Brain Tumors - National Cancer Institute |
      | page.language                               | english                                                                                 |
      | page.type                                   | nciAppModulePage                                                                        |
      | page.channel                                | Clinical Trials                                                                         |
      | page.contentGroup                           | Clinical Trials: Custom                                                                 |
      | page.publishedDate                          | 02/02/2011                                                                              |
      | page.additionalDetails.numberResults        | [(int) results total]                                                                   |
      | page.additionalDetails.trialListingPageType | manual parameters                                                                                  |

```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- [x] Story: No Trials Found for Manual Listing Pages #23

### Tasks
- [x] Results display - @alerosad 
- [x] Results styling - @seyilonge-nci 
- [x] Location display function @seyilonge-nci 
- [x] Unit tests - @seyilonge-nci 
- [x] Integration tests - @kate-mashkina 

### Technical Notes
- More notes, or technical nuances/direction
