### ISSUE TITLE
Story: No Trials Found Page for Manual Listing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#23]
## As a user, I want to know what other options are available for me if there are no matching trials for a manual listing page, so that I can further engage with NCI.

> **ESTIMATE** 2 pts

### Acceptance Criteria

```gherkin
Scenario: No trials found for manual listing page
Given user navigates to “/”
When no trials are returned for the manual listing page
Then the system displays the H1
  Then the system displays the message: “There are currently no available trials.”
```
```gherkin
   Scenario: Page Load Analytics fires when a user views a manual listing page
    Given "trialListingPageType" is set to "Manual"
      And "pageTitle" is set to "Clinical Trials for Adult Metastatic Brain Tumors"
      And "analyticsPublishedDate" is set to "02/02/2011"
     When the user navigates to "/"
     Then the page title is "Clinical Trials for Adult Metastatic Brain Tumors"
      And browser waits
     Then there should be an analytics event with the following details
      | key                                         | value                                                                         | 
      | type                                        | PageLoad                                                                      | 
      | event                                       | TrialListingApp:Load:Results                                                  | 
      | page.name                                   | www.cancer.gov/                                                               | 
      | page.title                                  | Clinical Trials for Adult Metastatic Brain Tumors                             | 
      | page.metaTitle                              | Clinical Trials for Adult Metastatic Brain Tumors - National Cancer Institute | 
      | page.language                               | english                                                                       | 
      | page.type                                   | nciAppModulePage                                                              | 
      | page.channel                                | Clinical Trials                                                               | 
      | page.contentGroup                           | Clinical Trials: Custom                                                       | 
      | page.publishedDate                          | 02/02/2011                                                                    | 
      | page.additionalDetails.numberResults        | (int)0                                                                        | 
      | page.additionalDetails.trialListingPageType | manual parameters                                                             |
```
### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Tasks
- [x] Add route for Manual listing view
- [x] Wire-up fetching for api calls - @seyilonge-nci 
- [x] Add No Results component - @sarinapadilla 
- [x] Unit tests - @sarinapadilla @seyilonge-nci 
- [x] Have `NoResults` component displayed for no trials match - @sarinapadilla 
- [x] Integration tests - @kate-mashkina 
- [x] Analytics - @kate-mashkina 

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Looks good to me! @mworrest - if you want to take a quick look :)
