### ISSUE TITLE
Story: Pager on disease DLP

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-listing-app#37]
## As a user, I want pager so that I can look through all of the results on dynamic listing pages.

Basically, add the pager to dynamic listing pages once code is complete for manual pages.

> **ESTIMATE** 3

### Acceptance Criteria

```gherkin
Scenario: Pager on dynamic listing page results with disease parameter only
  Given the user navigates to "/C4872"
  And "trialListingPageType" is set to "Disease"
    Then the page title is "Breast Cancer Clinical Trials"
   Then the system displays "Trials 1-25 of" "912"
    And the top pager is aligned to right on the same line as the number of trials on desktop
   And the bottom pager is aligned to right
    And pager displays the following navigation options
      | pages  |
      | 1      |
      | 2      |
      | 3      |
      | ...    |
      | 37     |
      | Next > |
    And the page "1" is highlighted
```

```gherkin
Scenario: Mobile and Tablet Pager Display
  Given user navigates to a listing page results URL
  Then the system returns the results page for cancer
    Then a horizontal rule is displayed below the "Trials 1-25 of XXX" 
    Then a top pager is displayed aligned to the left
    Then a horizontal rule is displayed below the pager
    Then the result items are displayed 
    Then a horizontal rule is displayed 
    Then the bottom pager is displayed aligned to the left
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Add Pager to `Disease`
- [ ] Update unit test for `Disease` to capture Pager
- [ ] Add integration tests

### Technical Notes
- More notes, or technical nuances/direction
